---
- name: Configure Kubernetes cluster
  hosts: tutorial
  roles:
    - role: lkummer.homelab.k3s
    - role: lkummer.homelab.prometheus
      vars:
        prometheus_grafana_host: grafana.example.com
        prometheus_grafana_user: admin
        # Use Ansible Vault for actual secrets!
        prometheus_grafana_password: admin
    - role: lkummer.homelab.argo
      vars:
        argo_host: argo.example.com
        argo_cert_manager_enabled: false
