---
collections:
  - name: community.general
    version: 8.0.2
  - name: community.crypto
    version: 2.16.0
  - name: kubernetes.core
    version: 3.0.0
  - name: lkummer.homelab
    type: git
    source: https://github.com/LKummer/ansible-collection-homelab.git
    version: 6.0.1
